export {
  alignCorrectionTexts,
  correctedTextFromPresentedAlignment,
  originalTextFromPresentedAlignment,
  type CorrectionChangeCandidate,
  type PresentedCorrectionSegment,
} from "./correction-alignment.js";
export {
  abandonedAttemptSchema,
  attemptFeedbackSchema,
  attemptInteractionSchema,
  attemptSchema,
  completedAttemptSchema,
  exerciseAnswerSchema,
  feedbackSourceSchema,
  feedbackUncertaintySchema,
  inProgressAttemptSchema,
  objectiveEvaluationSchema,
  objectiveOutcomeSchema,
  type Attempt,
  type AttemptFeedback,
  type AttemptInteraction,
  type ExerciseAnswer,
  type FeedbackUncertainty,
  type ObjectiveEvaluation,
} from "./attempt.js";
export { systemClock, type Clock } from "./clock.js";
export {
  curriculumCoverageSchema,
  curriculumDomains,
  curriculumDomainSchema,
  curriculumFilesystemLayout,
  curriculumManifestSchema,
  curriculumReadPolicySchema,
  curriculumSourceIdSchema,
  curriculumSourceRegistrySchema,
  curriculumSourceSchema,
  curriculumTopicFrontMatterSchema,
  type CurriculumManifest,
  type CurriculumSourceRegistry,
  type CurriculumTopicFrontMatter,
} from "./curriculum.js";
export {
  curriculumGapSelectionSchema,
  selectNextCurriculumGap,
  type CurriculumGapSelection,
} from "./curriculum-gap.js";
export {
  alignedCorrectionSegmentSchema,
  correctedTextFromCorrection,
  correctionCategories,
  correctionCategorySchema,
  correctionFollowUpSchema,
  correctionPrioritySchema,
  correctionSchema,
  correctionSeveritySchema,
  correctionVocabularyCandidateSchema,
  naturalAlternativeSchema,
  originalTextFromCorrection,
  type AlignedCorrectionSegment,
  type Correction,
  type CorrectionCategory,
  type CorrectionVocabularyCandidate,
} from "./correction.js";
export {
  aiProvenanceSchema,
  defaultFeedbackModeForExerciseKind,
  exerciseArtifactSchema,
  exerciseDefinitionSchema,
  exerciseKindSchema,
  exerciseKinds,
  feedbackModeSchema,
  feedbackModes,
  fillInTheBlankExerciseSchema,
  freeWritingExerciseSchema,
  generatedExerciseSchema,
  generatedLessonSchema,
  hintSchema,
  learningObjectiveSchema,
  lessonArtifactSchema,
  lessonDefinitionSchema,
  lessonIntentSchema,
  lessonKindSchema,
  lessonKinds,
  lessonSectionSchema,
  multipleChoiceExerciseSchema,
  sentenceCorrectionExerciseSchema,
  shortAnswerExerciseSchema,
  startedExerciseSnapshotSchema,
  startedLessonSnapshotSchema,
  vocabularySetLinkSchema,
  vocabularyRecallExerciseSchema,
  type AiProvenance,
  type ExerciseArtifact,
  type ExerciseDefinition,
  type ExerciseKind,
  type LessonArtifact,
  type LessonDefinition,
  type LessonKind,
  type StartedExerciseSnapshot,
  type StartedLessonSnapshot,
} from "./exercise.js";
export {
  evaluateExerciseAnswer,
  exerciseEvaluationSchema,
  type ExerciseEvaluation,
} from "./exercise-engine.js";
export {
  materializeGeneratedExercise,
  materializeGeneratedExerciseSet,
  materializeGeneratedLesson,
} from "./generated-exercise.js";
export {
  cefrBandSchema,
  cefrBands,
  correctionCoverageSchema,
  correctionPreferencesSchema,
  correctionTimingSchema,
  createInitialLearnerProfile,
  defaultTeachingProfileIdSchema,
  defaultUiLocale,
  learnerProfileSchema,
  levelEstimateSchema,
  levelBasisSchema,
  onboardingStateSchema,
  profileInsightSchema,
  teachingLanguageSchema,
  uiLocaleSchema,
  type CefrBand,
  type CorrectionPreferences,
  type DefaultTeachingProfileId,
  type LearnerProfile,
  type LevelEstimate,
  type ProfileInsight,
} from "./learner-profile.js";
export {
  defaultTeachingProfileForActivity,
  resolveTeachingProfile,
  sessionTeachingProfileSelectionSchema,
  teachingActivityKindSchema,
  teachingActivityKinds,
  teachingProfileDefinitionSchema,
  teachingProfileIdSchema,
  teachingProfileIds,
  teachingProfiles,
  type EffectiveTeachingProfile,
  type SessionTeachingProfileSelection,
  type TeachingActivityKind,
  type TeachingProfileDefinition,
  type TeachingProfileId,
} from "./teaching-profile.js";
export {
  defaultModelPreferences,
  effortChoiceSchema,
  modelChoiceSchema,
  modelPreferenceResolutionSchema,
  modelPreferencesSchema,
  modelWorkloadSchema,
  modelWorkloads,
  resolveModelPreference,
  runtimeEffortIdSchema,
  runtimeModelIdSchema,
  semanticEffortSchema,
  semanticEffortSemantics,
  semanticEfforts,
  unavailableRuntimeCapabilitySchema,
  unavailableSavedChoiceSchema,
  workloadModelPreferenceSchema,
  type EffortChoice,
  type ModelChoice,
  type ModelPreferenceResolution,
  type ModelPreferences,
  type ModelWorkload,
  type SemanticEffort,
  type WorkloadModelPreference,
} from "./model-preference.js";
export {
  deleteMistakeCommandSchema,
  effectiveMistakeCategory,
  mistakeCategorySchema,
  mistakeClassificationSchema,
  mistakeDispositionSchema,
  mistakeEvidenceSpanSchema,
  mistakeOccurrenceSchema,
  mistakeOccurrences,
  mistakeRecurrenceSchema,
  mistakeSchema,
  targetedPracticeLinkSchema,
  type DeleteMistakeCommand,
  type Mistake,
  type MistakeCategory,
  type MistakeOccurrence,
} from "./mistake.js";
export {
  vocabularyEntrySchema,
  vocabularyExampleSchema,
  vocabularyLexemeSchema,
  vocabularyReviewGrades,
  vocabularyReviewGradeSchema,
  vocabularyReviewScheduleSchema,
  vocabularyReviewSchema,
  scheduleVocabularyReview,
  vocabularyCandidateOriginSchema,
  vocabularyCandidateSchema,
  vocabularyEntryFromCandidate,
  vocabularyLessonSetRequestSchema,
  vocabularySourceSchema,
  vocabularyStateSchema,
  type VocabularyCandidate,
  type VocabularyEntry,
  type VocabularyLexeme,
  type VocabularyLessonSetRequest,
  type VocabularyReview,
  type VocabularySource,
  type VocabularyReviewGrade,
  type VocabularyReviewSchedule,
} from "./vocabulary.js";
export {
  weeklyPlanActivityContextSchema,
  weeklyPlanActivityKindSchema,
  weeklyPlanActivityKinds,
  weeklyPlanGoalSchema,
  selectWeeklyPlanRecommendation,
  weeklyPlanRecommendationSchema,
  weeklyPlanSchema,
  weeklyPlanSuggestedActivitySchema,
  type WeeklyPlan,
  type WeeklyPlanActivityKind,
  type WeeklyPlanGoal,
  type WeeklyPlanRecommendation,
  type WeeklyPlanSuggestedActivity,
} from "./weekly-plan.js";
export {
  voiceNextStepSchema,
  voiceObservedIssueCategories,
  voiceObservedIssueCategorySchema,
  voiceObservedIssueSchema,
  voiceSessionDurationSchema,
  voiceSessionFeedbackSchema,
  voiceSummarySchema,
  voiceVocabularyItemSchema,
  type VoiceObservedIssue,
  type VoiceSummary,
  type VoiceVocabularyItem,
} from "./voice-summary.js";
