// Generated by scripts/generate-css-types.mjs from renderer CSS modules.
declare module "*AppShell.module.css" {
  const styles: {
    readonly brand: string;
    readonly brandMark: string;
    readonly brandText: string;
    readonly helper: string;
    readonly helperCollapsed: string;
    readonly helperContent: string;
    readonly helperHeader: string;
    readonly helperInner: string;
    readonly nav: string;
    readonly navButton: string;
    readonly navCollapsed: string;
    readonly navFooter: string;
    readonly navInner: string;
    readonly navLabel: string;
    readonly navList: string;
    readonly shell: string;
    readonly wide: string;
    readonly workspace: string;
    readonly workspaceHeader: string;
    readonly workspaceInner: string;
  };
  export default styles;
}

declare module "*AppStyles.module.css" {
  const styles: {
    readonly startupCard: string;
  };
  export default styles;
}

declare module "*Button.module.css" {
  const styles: {
    readonly button: string;
    readonly buttonIcon: string;
    readonly content: string;
    readonly danger: string;
    readonly iconButton: string;
    readonly primary: string;
    readonly quiet: string;
    readonly secondary: string;
    readonly spinner: string;
    readonly tooltip: string;
    readonly visuallyHidden: string;
  };
  export default styles;
}

declare module "*ContextualHelper.module.css" {
  const styles: {
    readonly eyebrow: string;
    readonly helperAnswer: string;
    readonly helperComposer: string;
    readonly helperComposerActions: string;
    readonly helperComposerHint: string;
    readonly helperConversation: string;
    readonly helperSelection: string;
    readonly helperTurns: string;
  };
  export default styles;
}

declare module "*CorrectionComparison.module.css" {
  const styles: {
    readonly correctedPriority: string;
    readonly correctionChange: string;
    readonly correctionHelper: string;
    readonly correctionMistake: string;
    readonly correctionMistakes: string;
    readonly correctionReady: string;
    readonly correctionText: string;
    readonly eyebrow: string;
    readonly inlineCorrection: string;
    readonly noChanges: string;
    readonly warningText: string;
  };
  export default styles;
}

declare module "*Dashboard.module.css" {
  const styles: {
    readonly suggestion: string;
    readonly suggestions: string;
    readonly summary: string;
  };
  export default styles;
}

declare module "*Dialog.module.css" {
  const styles: {
    readonly actions: string;
    readonly body: string;
    readonly dialog: string;
    readonly overlay: string;
  };
  export default styles;
}

declare module "*DiffView.module.css" {
  const styles: {
    readonly grid: string;
    readonly inline: string;
  };
  export default styles;
}

declare module "*Disclosure.module.css" {
  const styles: {
    readonly content: string;
    readonly disclosure: string;
  };
  export default styles;
}

declare module "*ExerciseEngine.module.css" {
  const styles: {
    readonly acceptedAnswers: string;
    readonly activeExercise: string;
    readonly exerciseActions: string;
    readonly exerciseAiFeedback: string;
    readonly exerciseBlanks: string;
    readonly exerciseCardHeader: string;
    readonly exerciseNavButton: string;
    readonly exerciseNavigation: string;
    readonly exercisePrompt: string;
    readonly eyebrow: string;
    readonly optionGroup: string;
  };
  export default styles;
}

declare module "*Feedback.module.css" {
  const styles: {
    readonly diagnostic: string;
    readonly error: string;
    readonly feedback: string;
    readonly info: string;
    readonly loadingDot: string;
    readonly success: string;
    readonly warning: string;
  };
  export default styles;
}

declare module "*Fields.module.css" {
  const styles: {
    readonly checkbox: string;
    readonly control: string;
    readonly description: string;
    readonly error: string;
    readonly field: string;
    readonly invalid: string;
    readonly optionCard: string;
    readonly optionGrid: string;
    readonly toggleGroup: string;
  };
  export default styles;
}

declare module "*HistoryPage.module.css" {
  const styles: {
    readonly advancedFilters: string;
    readonly advancedGrid: string;
    readonly correctionGrid: string;
    readonly correctionPane: string;
    readonly correctionText: string;
    readonly eyebrow: string;
    readonly historyDetail: string;
    readonly historyEntryHeader: string;
    readonly historyEvidenceList: string;
    readonly historyList: string;
    readonly historyMistakeGrid: string;
    readonly page: string;
  };
  export default styles;
}

declare module "*InfoHint.module.css" {
  const styles: {
    readonly dialog: string;
    readonly hidden: string;
    readonly popover: string;
    readonly trigger: string;
  };
  export default styles;
}

declare module "*Layout.module.css" {
  const styles: {
    readonly actions: string;
    readonly description: string;
    readonly eyebrow: string;
    readonly fillLast: string;
    readonly filterBar: string;
    readonly grid: string;
    readonly header: string;
    readonly heading: string;
    readonly page: string;
    readonly section: string;
    readonly sectionHeading: string;
    readonly stack: string;
    readonly stackCompact: string;
    readonly title: string;
    readonly twoColumns: string;
    readonly wide: string;
  };
  export default styles;
}

declare module "*LearningPathPage.module.css" {
  const styles: {
    readonly explanation: string;
    readonly outline: string;
    readonly page: string;
    readonly unit: string;
    readonly words: string;
  };
  export default styles;
}

declare module "*OperationProgress.module.css" {
  const styles: {
    readonly attempt: string;
    readonly copy: string;
    readonly detail: string;
    readonly indicator: string;
    readonly progress: string;
  };
  export default styles;
}

declare module "*PersonalDataPage.module.css" {
  const styles: {
    readonly count: string;
    readonly description: string;
    readonly folder: string;
    readonly path: string;
    readonly reset: string;
    readonly table: string;
    readonly tableWrap: string;
  };
  export default styles;
}

declare module "*PracticePage.module.css" {
  const styles: {
    readonly backButton: string;
    readonly countBadge: string;
    readonly eyebrow: string;
    readonly generatedActivity: string;
    readonly generatedActivityCopy: string;
    readonly generatedActivityDelete: string;
    readonly generatedActivityList: string;
    readonly generatedActivityOpen: string;
    readonly generatedLibrary: string;
    readonly historyDetail: string;
    readonly inlineActions: string;
    readonly libraryFilterButton: string;
    readonly libraryFilters: string;
    readonly page: string;
    readonly practiceContent: string;
    readonly practiceLessonBody: string;
    readonly practiceLessonDisclosure: string;
    readonly practiceRunner: string;
    readonly practiceSection: string;
    readonly practiceSectionHeader: string;
    readonly practiceSession: string;
    readonly practiceSessionHeader: string;
    readonly practiceSessionMeta: string;
    readonly practiceSessionTitleRow: string;
    readonly practiceTypeCard: string;
    readonly practiceTypeCopy: string;
    readonly practiceTypeGrid: string;
    readonly practiceTypeIcon: string;
    readonly quizLength: string;
    readonly quizLengthButton: string;
    readonly quizLengthOptions: string;
    readonly readingPassage: string;
    readonly voicePreparation: string;
    readonly voicePreparedPreview: string;
    readonly voiceScenarioField: string;
    readonly voiceSetupGrid: string;
  };
  export default styles;
}

declare module "*ProfileOnboarding.module.css" {
  const styles: {
    readonly app: string;
    readonly controlLegend: string;
    readonly eyebrow: string;
    readonly languageButton: string;
    readonly onboardingCard: string;
    readonly onboardingGrid: string;
    readonly onboardingSection: string;
    readonly optionGroup: string;
    readonly startup: string;
    readonly startupCard: string;
    readonly topActions: string;
  };
  export default styles;
}

declare module "*SettingsPage.module.css" {
  const styles: {
    readonly detailList: string;
    readonly modelRow: string;
    readonly sectionNav: string;
    readonly settingsActions: string;
    readonly settingsControls: string;
    readonly settingsPage: string;
    readonly switchConfirmation: string;
  };
  export default styles;
}

declare module "*SidebarModelControl.module.css" {
  const styles: {
    readonly navModelEffortButton: string;
    readonly navModelEffortGrid: string;
    readonly navModelError: string;
    readonly navModelField: string;
    readonly navModelHeading: string;
    readonly navModelPanel: string;
    readonly navModelReasoning: string;
    readonly navModelStatus: string;
    readonly navModelWorkloadButton: string;
    readonly navModelWorkloads: string;
  };
  export default styles;
}

declare module "*Startup.module.css" {
  const styles: {
    readonly app: string;
    readonly eyebrow: string;
    readonly languageButton: string;
    readonly privacyGrid: string;
    readonly startup: string;
    readonly startupCard: string;
    readonly topActions: string;
    readonly warningList: string;
  };
  export default styles;
}

declare module "*Surface.module.css" {
  const styles: {
    readonly card: string;
    readonly empty: string;
    readonly itemList: string;
    readonly muted: string;
    readonly mutedText: string;
  };
  export default styles;
}

declare module "*Tabs.module.css" {
  const styles: {
    readonly list: string;
    readonly panel: string;
    readonly tab: string;
    readonly tabs: string;
  };
  export default styles;
}

declare module "*VocabularyPage.module.css" {
  const styles: {
    readonly caption: string;
    readonly compactDue: string;
    readonly compactMeaning: string;
    readonly dueColumn: string;
    readonly editForm: string;
    readonly empty: string;
    readonly meaningColumn: string;
    readonly muted: string;
    readonly reviewCard: string;
    readonly selection: string;
    readonly sort: string;
    readonly summary: string;
    readonly table: string;
    readonly tableRegion: string;
    readonly toolbar: string;
    readonly word: string;
  };
  export default styles;
}

declare module "*WritingWorkspace.module.css" {
  const styles: {
    readonly draftNotice: string;
    readonly eyebrow: string;
    readonly generatedPrompt: string;
    readonly promptActionButtons: string;
    readonly promptActions: string;
    readonly selectionStatus: string;
    readonly writingEditor: string;
    readonly writingLayout: string;
    readonly writingOptions: string;
    readonly writingTextarea: string;
  };
  export default styles;
}
